apiVersion: apps/v1
kind: Deployment
metadata:
  name: metric-database
  labels:
    app: metric-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metric-database
  template:
    metadata:
      labels:
        app: metric-database
    spec:
      containers:
        - name: metric
          image: postgres:9.6
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: postgres
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/
              name: init-script
      volumes:
        - name: init-script
          configMap:
            defaultMode: 420
            name: metric-database-init-script
