apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-dashboard
  labels:
    app: grafana-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-dashboard
  template:
    metadata:
      labels:
        app: grafana-dashboard
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:6.6.2
          ports:
            - containerPort: 3000
              name: http
