apiVersion: v1
kind: Service
metadata:
  name: grafana-dashboard
  labels:
    app: grafana-dashboard
spec:
  selector:
    app: grafana-dashboard
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  type: LoadBalancer
